export const allCardsData = [
  {
    name: "Gather wood",
    id: 1,
    description: "Gathers wood depending on terrain",
    cost: "",
    workers: 1,
    wood: 0,
    stone: 0,
  },
  {
    name: "Gather stone",
    id: 2,
    description: "Gathers stone depending on terrain",
    cost: "",
    workers: 1,
    wood: 0,
    stone: 0,
  },
  {
    name: "Gather coconuts",
    id: 3,
    description: "Gathers food depending on terrain",
    cost: "",
    workers: 1,
    wood: 0,
    stone: 0,
  },
  {
    name: "Lumberhut",
    id: 4,
    description: "Gathers wood",
    cost: "",
    workers: 1,
    wood: 8,
    stone: 0,
  },
  {
    name: "Big hut",
    id: 5,
    description: "Adds 2 workers",
    cost: "",
    workers: 1,
    wood: 0,
    stone: 0,
  },
  {
    name: "Watch tower",
    id: 6,
    description: "Gathers wood",
    cost: "",
    workers: 1,
    wood: 0,
    stone: 4,
  },
];
