export const dataLevel3 = {
  levelText: "Level 3 - Find treasures",
  text: [
    "Well, that was not the task. Maybe you're not ready for the island yet. Please restart the tutorial...",
    "Welcome back, adventurer. Let's take a look on how much you've learned so far. We think that there are some treasures hidden in this jungle. Try your best and find them!",
    "Great! With all that water out of the way, we can continue our search for treasures!",
  ],
  tasks: [
    "",
    "Build a water tower.",
    "Build a water tower.",
    "Build a water tower.",
  ],
  fields: [
    {
      id: 0,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 1,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 3,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 4,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 5,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 6,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 7,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 8,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 9,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 10,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 11,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 13,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 14,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 15,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 16,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 17,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 18,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 19,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 20,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 21,
      color: "forest",
      secondcolor: "water",
      red: true,
      show: true,
    },
    {
      id: 22,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 23,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 24,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 25,
      color: "lumberhut",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 26,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 27,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 28,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 29,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 30,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 31,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 32,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 33,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 34,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 37,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 38,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 39,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 40,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 41,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 42,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 43,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 44,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 45,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 46,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 47,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 48,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 49,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 50,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 51,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 52,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 53,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 54,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 55,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 56,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 57,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 58,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 59,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 60,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 61,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 62,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 63,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 64,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 65,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 66,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 67,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 68,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 69,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
  ],
};
