export const dataLevel1 = {
  levelText: "Level 1 - Building basics",
  text: [
    "Well, that was not the task. Maybe you're not ready for the island yet. Please restart the tutorial...",
    "Welcome to the island! Let's find out what kind of treasures hide in this tropical jungle! Your first task is to build a lumberhut. Simply click on the sand tile, choose the lumberhut from the menu and build!",
    "Well done! Every day the lumberhut cuts down trees that are next to the tile it's placed on and leaves more space for new buildings. Each chopped tree gives you one wood, but the lumberhut itself costs two wood, so be careful...",
    "After all trees have been chopped down, go on and build a second lumberhut on the right sand tile.",
    "Great! Now wait for all trees to be chopped down. Do you notice, that the right rock tile didn't change? Lumberhuts can only chop trees.",
    "Seems like you've discovered some fresh water sources under the trees. We need to destroy the first lumberhut again to get enough space for a water tower.",
  ],
  tasks: [
    "",
    "Build a lumberhut.",
    "Build a lumberhut",
    "Build a second lumberhut on the right sand tile",
    "Build a second lumberhut on the right sand tile",
    "Destroy the left lumberhut",
    "Destroy the left lumberhut",
  ],
  fields: [
    {
      id: 0,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 1,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 3,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 4,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 5,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 6,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 7,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 8,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 9,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 10,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 11,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 13,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 14,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 15,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 16,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 17,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 18,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 19,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 20,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 21,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 22,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 23,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 24,
      color: "grass",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 25,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 26,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 27,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 28,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 29,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 30,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 31,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 32,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 33,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 34,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 37,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 38,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 39,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 40,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 41,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 42,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 43,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 44,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 45,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 46,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 47,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 48,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 49,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
  ],
};
