export const dataLevel2 = {
  levelText: "Level 2 - Build a water tower",
  text: [
    "Well, that was not the task. Maybe you're not ready for the island yet. Please restart the tutorial...",
    "On this island, fresh water sources are blocking our way. You need to build a water tower to pump the water. It needs two tiles of space, so the building tile should have an empty tile underneath it.",
    "Great! With all that water out of the way, we can continue our search for treasures!",
  ],
  tasks: [
    "",
    "Build a water tower.",
    "Build a water tower.",
    "Build a water tower.",
  ],
  fields: [
    {
      id: 0,
      color: "grass",
      dark: false,
      show: true,
    },
    {
      id: 1,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 3,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 4,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 5,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 6,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 7,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 8,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 9,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 10,
      color: "house",
      dark: false,
      show: true,
    },
    {
      id: 11,
      color: "lumberhut",
      dark: false,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 13,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 14,
      color: "water",
      dark: false,
      show: true,
    },
    {
      id: 15,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 16,
      color: "stone",
      dark: false,
      show: true,
    },
    {
      id: 17,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 18,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 19,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 20,
      color: "windmill",
      dark: false,
      show: true,
    },
    {
      id: 21,
      color: "wheat",
      dark: false,
      show: true,
    },
    {
      id: 22,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 23,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 24,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 25,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 26,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 27,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 28,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 29,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 30,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 31,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 32,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 33,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 34,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 37,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 38,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 39,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 40,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 41,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 42,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 43,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 44,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 45,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 46,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 47,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 48,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 49,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 50,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 51,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 52,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 53,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 54,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 55,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 56,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 57,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 58,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 59,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 60,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 61,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 62,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 63,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 64,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 65,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 66,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 67,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 68,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 69,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 70,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 71,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 72,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 73,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 74,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 75,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 76,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 77,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 78,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 79,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 80,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 81,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 82,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 83,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 84,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 85,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 86,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 87,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 88,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 89,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 90,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 91,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 92,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 93,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 94,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 95,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 96,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 97,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 98,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 99,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 100,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 101,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 102,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 103,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 104,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 105,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 106,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 107,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 108,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 109,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 110,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 111,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 112,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 113,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 114,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 115,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 116,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 117,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 118,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 119,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 120,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 121,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 122,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 123,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 124,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 125,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 126,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 127,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 128,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 129,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 130,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 131,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 132,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 133,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 134,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 135,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 136,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 137,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 138,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 139,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 140,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 141,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 142,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 143,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 144,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 145,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 146,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 147,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 148,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 149,
      color: "water",
      dark: true,
      show: true,
    },
  ],
};
