export const dataLevel3 = {
  levelText: "Level 3 - Upgrade a tent to a house",
  fields: [
    {
      id: 0,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 1,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 3,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 4,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 5,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 6,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 7,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 8,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 9,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 10,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 11,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 13,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 14,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 15,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 16,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 17,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 18,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 19,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 20,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 21,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 22,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 23,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 24,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 25,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 26,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 27,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 28,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 29,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 30,
      color: "grass",
      dark: false,
      show: true,
    },
    {
      id: 31,
      color: "house",
      dark: false,
      show: true,
    },
    {
      id: 32,
      color: "stone",
      dark: false,
      show: true,
    },
    {
      id: 33,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 34,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 37,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 38,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 39,
      color: "stone",
      dark: true,
      show: true,
    },
  ],
};
