export const dataLevel2 = {
  levelText: "Level 2 - Build a water tower",
  text: [
    "Well, that was not the task. Maybe you're not ready for the island yet. Please restart the tutorial...",
    "On this island, fresh water sources are blocking our way. You need to build a water tower to pump the water. It needs two tiles of space, so the building tile should have an empty tile underneath it.",
    "Great! With all that water out of the way, we can continue our search for treasures!",
  ],
  tasks: [
    "",
    "Build a water tower.",
    "Build a water tower.",
    "Build a water tower.",
  ],
  fields: [
    {
      id: 0,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 1,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 3,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 4,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 5,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 6,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 7,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 8,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 9,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 10,
      color: "grass",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 11,
      color: "water",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 13,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 14,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 15,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 16,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 17,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 18,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 19,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 20,
      color: "lumberhut",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 21,
      color: "grass",
      secondcolor: "water",
      red: true,
      show: true,
    },
    {
      id: 22,
      color: "water",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 23,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 24,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 25,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 26,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 27,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 28,
      color: "stone",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 29,
      color: "stone",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 30,
      color: "grass",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 31,
      color: "grass",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 32,
      color: "water",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 33,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 34,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 37,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 38,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 39,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 40,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 41,
      color: "water",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 42,
      color: "forest",
      secondcolor: "stone",
      red: false,
      show: true,
    },
    {
      id: 43,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 44,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 45,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 46,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 47,
      color: "forest",
      secondcolor: "grass",
      red: false,
      show: true,
    },
    {
      id: 48,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
    {
      id: 49,
      color: "forest",
      secondcolor: "water",
      red: false,
      show: true,
    },
  ],
};
