export const freePlayData = {
  levelText: "Free play",
  fields: [
    {
      id: 0,
      color: "grass",
      dark: false,
      show: true,
    },
    {
      id: 1,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 2,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 3,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 4,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 5,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 6,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 7,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 8,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 9,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 10,
      color: "house",
      dark: false,
      show: true,
    },
    {
      id: 11,
      color: "forest",
      dark: false,
      show: true,
    },
    {
      id: 12,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 13,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 14,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 15,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 16,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 17,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 18,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 19,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 20,
      color: "grass",
      dark: false,
      show: true,
    },
    {
      id: 21,
      color: "grass",
      dark: false,
      show: true,
    },
    {
      id: 22,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 23,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 24,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 25,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 26,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 27,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 28,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 29,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 30,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 31,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 32,
      color: "water",
      dark: true,
      show: true,
    },
    {
      id: 33,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 34,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 35,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 36,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 37,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 38,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 39,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 40,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 41,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 42,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 43,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 44,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 45,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 46,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 47,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 48,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 49,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 50,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 51,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 52,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 53,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 54,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 55,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 56,
      color: "grass",
      dark: true,
      show: true,
    },
    {
      id: 57,
      color: "stone",
      dark: true,
      show: true,
    },
    {
      id: 58,
      color: "forest",
      dark: true,
      show: true,
    },
    {
      id: 59,
      color: "forest",
      dark: true,
      show: true,
    },
  ],
};
